AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  video-handler

  Sample SAM Template for video-handler

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Parameters:
  #   EndpointConfigType:
  #     Type: String
  #     Default: PRIVATE
  VpcEndpointId:
    Type: String
  FfmpegLayerARN:
    Type: String

Resources:
  ExplicitApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: 
        Type: PRIVATE
        VPCEndpointIds:
          - !Ref VpcEndpointId
      Auth:
        ResourcePolicy:
          CustomStatements: {
              Effect: 'Allow',
              Action: 'execute-api:Invoke', 
              Resource: ['execute-api:/*/*/*'],
              Principal: '*'
            }
  VideoHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: video_handler/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: VideoHandlerFunction
      Environment:
        Variables:
          OutPutBucket: ""
          OutPutPath: ""
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: "*"
        - S3WritePolicy:
            BucketName: "*"
        - CloudWatchFullAccess
      Layers:
        - !Ref FfmpegLayerARN
  APIVideoHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: video_handler/
      Handler: app.video_api_handler
      Runtime: python3.9
      FunctionName: VideoHandlerAPIFunction
      Environment:
        Variables:
          OutPutBucket: ""
          OutPutPath: "" # a/b/c, c后不需要有/
      Layers:
        - !Ref FfmpegLayerARN
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: "*"
        - S3WritePolicy:
            BucketName: "*"
        - CloudWatchFullAccess
      Events:
        VideoHandler:
          Type: Api # More info about API Event Source: https://github.com/anwslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: 
              Ref: ExplicitApi
            Path: /VideoHandler
            Method: post

Outputs:
  ApiGatewayInvokeURL:
    Description: "API Gateway endpoint URL for Prod stage for VideoHandlerFunction function"
    Value: !Sub "https://${ExplicitApi.RestApiId}.execute-api.${AWS::Region}.amazonaws.com/${ExplicitApi.Stage}/VideoHandler/"
  VideoHandlerFunction:
    Description: "Video Handler Lambda Function ARN"
    Value: !GetAtt VideoHandlerFunction.Arn
  VideoHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Video Handler function"
    Value: !GetAtt VideoHandlerFunctionRole.Arn
